require 'user.options'
require 'user.keymaps'
require 'user.autocommands'
require 'user.plugins'
require 'user.bufferline'
require 'user.colorscheme'
require 'user.comment'
require 'user.gitsigns'
require 'user.telescope'
require 'user.nvimtree'
require 'user.treesitter'
require 'user.indent_blankline'
require 'user.lualine'

require 'user.lsp'
