require 'user.options'
require 'user.keymaps'
require 'user.autocommands'
require 'user.plugins'
--require 'user.bufferline'
--require 'user.colorscheme'
--require 'user.comment'
--require 'user.telescope'
--require 'user.treesitter'
--require 'user.indent_blankline'
--require 'user.lualine'

--require 'user.lsp'
