#!/bin/sh
export HISTFILE=$HOME/.cache/zsh/.zsh_history
export HISTSIZE=1000000
export SAVEHIST=1000000

export PATH="$HOME/.local/bin":$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go

eval "$(zoxide init zsh)"
